["general"]
includes = ["co:bun", "co:git"]

["dev:doc"]
commands = ["dev:doc"]
scripts = ['''
    cd ./packages/milkio-doc
    && bun run docs:dev
''']

["publish"]
commands = ["publish", "p"]
scripts = ['''
    cd ./packages/milkio
    && npm version patch
    && npm publish --access public
''']

["publish:redis"]
commands = ["publish:redis", "p:r"]
scripts = ['''
    cd ./packages/milkio-redis
    && npm version patch
    && npm publish --access public
''']

["publish:drizzle"]
commands = ["publish:drizzle", "p:d"]
scripts = ['''
    cd ./packages/milkio-drizzle
    && npm version patch
    && npm publish --access public
''']

["publish:template"]
commands = ["publish:template", "p:t"]
scripts = ['''
    cd ./packages/milkio-template
    && npm version patch
    && npm publish --access public
''']

["publish:client"]
commands = ["publish:client", "p:c"]
scripts = ['''
    cd ./packages/milkio-client
    && bun run build
    && npm version patch
    && npm publish --access public
''']

["publish:doc"]
commands = ["publish:doc", "publ:doc", "p:doc"]
scripts = ['''
    cd ./packages/milkio-doc
    && bun run docs:build
    && cd ../..
    && git add --all
    && git commit -m <%= JSON.stringify(
        "📝 doc: "+
        await ui({
            type: "input",
            message: 'Enter commit message',
            initial: 'update'
        })
    ) %>
    && git push
''']

["publish:docker"]
commands = ["publish:docker", "publ:docker", "p:docker"]
scripts = [
    '''
    <% var now = day().format('YYYY-MM-DD-T-HH-mm-ss') %>
    cd ./packages/milkio-docker
    && docker build -t kecream/milkio:v1 -t kecream/milkio:<%= now %> -t kecream/milkio:latest .
    && docker push kecream/milkio:latest
    && docker push kecream/milkio:v1
    && docker push kecream/milkio:<%= now %>
''',
]
