name: milkio
on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version'
        required: true
env:
  ACTION_VERSION: linux-x64
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.1.14"
          registry-url: "https://registry.npmjs.org/"
      - name: Publish
        env:
          NPM_PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: >-
          cd ./packages/milkio
          && echo $ACTION_VERSION
          && echo $BUN_AUTH_TOKEN
          && echo "//registry.npmjs.org/:_authToken=$BUN_AUTH_TOKEN"
          && pwd && ls
          && bun install --frozen-lockfile
          && npm set "//registry.npmjs.org/:_authToken=$BUN_AUTH_TOKEN"
          && npm publish --new-version "$NPM_PACKAGE_VERSION"
